apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheep-dog-asciidoc-api-svc-pvc
  labels:
    app: sheep-dog
    component: sheep-dog-asciidoc-api-svc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheep-dog-cucumber-gen-svc-pvc
  labels:
    app: sheep-dog
    component: sheep-dog-cucumber-gen-svc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
