apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: svc-pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: sheep-dog-asciidoc-api-svc-pvc
  - path: svc-pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: sheep-dog-cucumber-gen-svc-pvc
