apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: service-patch-db.yaml
    target:
      kind: Service
      name: sheep-dog-dev-db
  - path: db-pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: sheep-dog-dev-db-pvc
  - path: svc-pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: sheep-dog-dev-svc-pvc 