apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheep-dog-db-pvc
  labels:
    app: sheep-dog
    component: sheep-dog-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
