name: E2E Test

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix for the stack name'
        required: true
        default: '1'

jobs:
  setup-cluster:
    uses: ./.github/workflows/setup-cluster.yml
    with:
      suffix: ${{ github.event.inputs.suffix }}

  forward-engineer:
    needs: setup-cluster
    uses: ./.github/workflows/forward-engineer.yml
    with:
      host: ${{ needs.setup-cluster.outputs.service_url }}
