name: E2E Test

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix for the stack name'
        required: true
        default: '1'

jobs:
  setup-stack:
    uses: ./.github/workflows/setup-stack.yml
    with:
      suffix: ${{ github.event.inputs.suffix }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  setup-cluster:
    needs: setup-stack
    uses: ./.github/workflows/setup-cluster.yml
    with:
      suffix: ${{ github.event.inputs.suffix }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      
  forward-engineer:
    needs: setup-cluster
    uses: ./.github/workflows/forward-engineer.yml
    with:
      host: ${{ needs.setup-cluster.outputs.service_url }}
