apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: db-pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: sheep-dog-db-pvc
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: sheep-dog-ingress
